exports.events = [
  { name: 'PointerPressed',
    description: 'A pointer pressed event has occurred.'},
  { name: 'PointerReleased',
    description: 'A pointer released event has occurred.'},
  { name: 'ContentLoaded',
    description: 'This event is not used and has been deprecated.'},
  { name: 'Clicked',
    description: 'Sent when something is clicked.'},
  { name: 'ItemClicked',
    description: 'Sent when an item in a list view is clicked.'},
  { name: 'TabChanged',
    description: 'Sent when a tab widget has changed to a new tab.'},
  { name: 'GLViewReady',
    description: 'Sent when an GLView has been initialized and is ready for setup.'},
  { name: 'WebViewURLChanged',
    description: 'Sent when the URL of a web view changes.'},
  { name: 'StackScreenPopped',
    description: 'Sent when a screen has been popped from a stack screen.'},
  { name: 'SliderValueChanged',
    description: 'Sent when the progress level has been changed. This includes changes that were initiated by the user through a touch gesture, or arrow key/trackball as well as changes that were initiated programmatically.'},
  { name: 'DatePickerValueChanged',
    description: 'Sent when the user changes the date in a Date Picker.'},
  { name: 'NumberPickerValueChanged',
    description: 'Sent when the user changes the time in a Time Picker.'},
  { name: 'VideoStateChanged',
    description: 'Sent when the user changes the value in a Number Picker.'},
  { name: 'EditBoxEditingDidBegin',
    description: 'Sent from the Video View when the state of the video has changed.'},
  { name: 'EditBoxEditingDidBegin',
    description: 'Sent from the Edit box when it gains focus(the user selects the widget). The virtual keyboard is shown.'},
  { name: 'EditBoxEditingDidEnd',
    description: 'Sent from the Edit box when it loses focus. The virtual keyboard is hidden.'},
  { name: 'EditBoxTextChanged',
    description: 'Sent from the Edit box when the text was changed.'},
  { name: 'EditBoxReturn',
    description: 'Sent from the Edit box when the return button was pressed. On iphone platform the virtual keyboard is not closed after receiving this event. The virtual keyboard can be hided by setting the "showKeyboard" to "false". Not available on Windows Phone 7.1.'},
  { name: 'WebViewHookInvoked',
    description: 'A web view hook has captured a url.'},
  { name: 'DialogDismissed',
    description: 'Send by a Dialog widget when when a user dismisses a popover by tapping outside of it. It will not be sent if it was dismissed by calling maWidgetModalDialogHide(). Available only on the iPad'}
];